### ISSUE TITLE
Allow retrieval of JSON response body for non-200 HTTP responses

### ISSUE THREAD

**Issue by kidambisrinivas** [evancz/elm-http#27] opened 2016-01-27 04:05 UTC
Hi, Could you help me read HTTP response body for a non 200 HTTP status

``` elm
getJson : String -> String -> Effects Action
getJson url credentials =
  Http.send Http.defaultSettings
    { verb = "POST"
    , headers = [("Authorization", "Basic " ++ credentials)]
    , url = url
    , body = Http.empty
    }
    |> Http.fromJson decodeAccessToken
    |> Task.toResult
    |> Task.map UpdateAccessTokenFromServer
    |> Effects.task
```

The above promotes the error from

``` elm
Task.toResult : Task Http.Error a -> Task x (Result Http.Error a)
```

The value of which becomes

(BadResponse 400 ("Bad Request"))

My server responds with what is wrong with the request as a JSON payload in the response body. Please help me retrieve that from the Task x a into ServerResult below.

``` elm
type alias ServerResult = { status : Int, message : String }
```

**Comment by aymanosman** [comment] 2016-02-09 22:51
You're going to have to not use `Http.fromJson`, which as the docs say checks the status code is in the 200 range.

http://package.elm-lang.org/packages/evancz/elm-http/3.0.0/Http#fromJson

Also see https://github.com/evancz/elm-http/blob/fb062e8db774e42070e94ee7591d105294a86bfc/src/Http.elm#L422-L445

which will give you an idea of what you'd need to replace to get what you want.

**Comment by martinos** [comment] 2016-02-23 19:46
I think that adding a `Response` to the `BadResponse` constructor of the `Error` type would make the `fromJson` function more flexible. 

``` elm
type Error
    = Timeout
    | NetworkError
    | UnexpectedPayload String
    | BadResponse Response
```

Instead of

``` elm
type Error
    = Timeout
    | NetworkError
    | UnexpectedPayload String
    | BadResponse Int String
```

I have noticed that there are some discussions about this subject on this #12 pull request.

**Comment by lukewestby** [comment] 2016-03-01 13:26
Hi folks, you can use [elm-http-extra](http://package.elm-lang.org/packages/lukewestby/elm-http-extra/latest) to do this until and if it is included in elm-http :smile:

**Comment by ccapndave** [comment] 2016-05-19 09:56
This is particularly important in the case of `status = 0` which is returned when accessing `file://` resources (this is even written in the source of Http.elm!)  In this case the response, which is actually fine, gets turned into a `BadResponse` and thrown away.

**Comment by ccapndave** [comment] 2016-05-19 15:12
It sounds like @lukewestby is planning to build this functionality into https://github.com/lukewestby/elm-http-builder so I'm not publishing this, but in the meantime here is a module that replaces `get` and `getString` with versions that accept 0 as a status code:

``` elm
module FileHttp exposing
  ( get
  , getString
  )

import Http
import HttpBuilder exposing (..)
import Json.Decode exposing (Decoder)
import Task exposing (Task, andThen, onError, mapError, map)

{-| Send a GET request to the given URL. You also specify how to decode the
response.
    import Json.Decode (list, string)
    hats : Task Error (List String)
    hats =
        get (list string) "http://example.com/hat-categories.json"

Unlike the standard library, an HTTP status code of 0 will *not* result in an error, but will
be intercepted and turned into a 200.  This allows you to access file:// resources transparently.
-}
get : Decoder value -> String -> Task Http.Error value
get decoder url =
  let
    getTask =
      HttpBuilder.get url
        |> send (jsonReader decoder) (jsonReader decoder)
  in
  makeTask getTask


{-| Send a GET request to the given URL. You will get the entire response as a
string.
    hats : Task Error String
    hats =
        getString "http://example.com/hat-categories.markdown"

Unlike the standard library, an HTTP status code of 0 will *not* result in an error, but will
be intercepted and turned into a 200.  This allows you to access file:// resources transparently.
-}
getString : String -> Task Http.Error String
getString url =
  --Task.succeed ""
  let
    getTask =
      HttpBuilder.get url
        |> send stringReader stringReader
  in
  makeTask getTask


{-| Given a task, return a new task that copes with status of 0
-}
makeTask : Task (Error r) (Response r) -> Task Http.Error r
makeTask task =
  task
    `onError` recoverIfStatusZero
    |> mapError builderErrorToHttpError
    |> map (\response -> response.data)


{-| Turn a Response with status 0 into a Response with status 200
-}
recoverIfStatusZero : Error r -> Task (Error r) (Response r)
recoverIfStatusZero error =
  case error of
    BadResponse response ->
      if (response.status == 0) then
        Task.succeed
          { data = response.data
          , status = 200
          , statusText = response.statusText
          , headers = response.headers
          , url = response.url
          }
      else
        Task.fail error

    _ ->
      Task.fail error


{-| Convert a HttpBuilder.Error into and Http.Error so that the rest of the application doesn't need to
know that anything has changed.
-}
builderErrorToHttpError : Error a -> Http.Error
builderErrorToHttpError error =
  case error of
    UnexpectedPayload str ->
      Http.UnexpectedPayload str

    NetworkError ->
      Http.NetworkError

    Timeout ->
      Http.Timeout

    BadResponse response ->
      Http.BadResponse response.status response.statusText
```

**Comment by magopian** [comment] 2016-09-05 15:47
I believe this issue can now be closed:
1/ it has some answers
2/ it's a question, not a bug ([issues are for bugs](https://github.com/process-bot/contribution-checklist/blob/master/issues.md#issues))

**Comment by esad** [comment] 2016-09-06 12:27
@magopian I think this is a valid request for a more complete implementation and not a random question

**Comment by ccapndave** [comment] 2016-09-06 12:50
@magopian Its an enhancement I suppose rather than a bug, but its missing functionality that requires either a fiddly workaround or using a different library.

**Comment by magopian** [comment] 2016-09-06 14:52
I stand corrected, sorry for the noise

**Comment by evancz** [comment] 2016-11-21 18:52
Should be fixed in elm-lang/http

**Closed as completed by evancz** 2016-11-21 18:52 UTC
